version: "3.9"

services:


  
  postgres_db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=Danik
      - POSTGRES_PASSWORD=polgaden12398
      - POSTGRES_DB=postsqlbd
    ports:
      - "5432:5432"

  webapp:
    restart: always
    #image: danik25/webappchat:latest
    build:
        ./
    depends_on: 
      - postgres_db
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:5001"
    ports:
      - "5001:5001"
  